name: spaced_repetition_notes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  #Utility
  flutter_iconpicker: ^3.2.4
  #Cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #Anim
  lottie: ^2.7.0
  #Font
  google_fonts: ^6.1.0
  #State Managament
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  #Utility  
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  #Lint 
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/